package de.hhu.stups.plues.routes;

public enum RouteNames {
  ABOUT_WINDOW,
  ABSTRACT_UNIT_DETAIL_VIEW,
  CHANGELOG,
  COURSE_DETAIL_VIEW,
  INDEX,
  MODULE_DETAIL_VIEW,
  PARTIAL_TIMETABLES,
  PDF_TIMETABLES,
  REPORTS,
  SESSION_DETAIL_VIEW,
  TIMETABLE,
  UNIT_DETAIL_VIEW,
  UNSAT_CORE,
  HANDBOOK_HTML,
  HANDBOOK_PDF;
}
